import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Header from '@/components/Header'
import Breadcrumb from '@/components/Breadcrumb'
import Footer from '@/components/Footer'
import { CartStoreProvider } from '@/providers/cart-store-provider'

const SVNGraphik = localFont({
  src: [
    {
      path: './fonts/SVN-GraphikExtralight.woff',
      weight: '200',
      style: 'normal',
    },
    {
      path: './fonts/SVN-GraphikBold.woff',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/SVN-GraphikSemibold.woff',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/SVN-Graphik.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/SVN-GraphikBlack.woff',
      weight: '700',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const breadcrumbItems = [
    { name: 'Bút cảm ứng', link: '#' },
    { name: '[Pencil Pro] Bút cảm ứng Stylus AstroMazing Pencil 2 Pro dành cho iPad Pro', link: '#' },
  ]

  return (
    <html lang='en'>
      <body className={`${SVNGraphik.className} antialiased bg-bg-elevation-10`}>
        <CartStoreProvider>
          <Header />
          <Breadcrumb items={breadcrumbItems} />
          {children}
          <Footer />
        </CartStoreProvider>
      </body>
    </html>
  )
}
